---
title: "rmarkdown(3)"
author: "Katie Clouse"
date: "2025-02-26"
output: 
  md_document:
    variant: gfm
  html_document:
    toc: true
    toc_float: true
  word_document:
  pdf_document:
    
---
This is an example or R code.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(ggplot2)
library(rmarkdown)
# this is R code
summary(mtcars)
```

This is how to include figures
```{r}
data("mtcars")
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_smooth(method= lm, se = FALSE)+
  geom_point(aes(color = wt)) +
  xlab("Weight")+
  ylab("Miles per Gallon")+
  scale_colour_gradient(low = "forestgreen", high = "black")
```




R markdown formatting options 

# first level header 
## Second level header
**this text is italics**. One asterisk is italics and two on each side is to make the lettering bold
### Third level header 


1. one item # if you type a dash and then a space you create a list. 
2.another item 
    - one subitem 






























